version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ComplexPassw0rd!
      MYSQL_DATABASE: domain_checker # Создание базы данных при старте
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    restart: always

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
